name: "plugin-tests"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:

jobs:
  # unit tests
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #- run: npm ci
    #- run: npm test

  # test action works running from the graph
  live-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        vht_in: ./VHT_suite_test
        instance_id: ${{ secrets.AWS_INSTANCE_ID }}
        aws_region: "eu-west-1"
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        session_token: ${{ secrets.AWS_SESSION_TOKEN }}
        s3_bucket_name: gh-vht

